---

# Create user & group to run matrix server
- name: Ensure Matrix group is created
  group:
    name: "{{ matrix_user_groupname }}"
    gid: "{{ omit if matrix_user_gid is none else matrix_user_gid }}"
    state: present
  register: matrix_group

- name: Set Matrix Group GID Variable
  set_fact:
    matrix_user_gid: "{{ matrix_group.gid }}"

- name: Ensure Matrix user is created
  user:
    name: "{{ matrix_user_username }}"
    uid: "{{ omit if matrix_user_uid is none else matrix_user_uid }}"
    state: present
    group: "{{ matrix_user_groupname }}"
  register: matrix_user

- name: Set Matrix Group UID Variable
  set_fact:
    matrix_user_uid: "{{ matrix_user.uid }}"

- name: Create app directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_app_directory }}"
    - "{{ matrix_data_directory }}"
    - "{{ postgres_data_directory }}"
    - "{{ synapse_data_directory }}"
    - "{{ riot_data_directory }}"

- name: Pull required images from docker hub
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ docker_image.matrix_synapse }}"
    - "{{ docker_image.postgres }}"
    - "{{ docker_image.wait_for_it }}"
