---

- name: Download release from Github
  get_url:
    url: 'https://github.com/vector-im/riot-web/releases/download/v{{ riot_web_version }}/riot-v{{ riot_web_version }}.tar.gz'
    dest: '{{ app_directory }}/riot-v{{ riot_web_version }}.tar.gz'

- name: Unarchive the app
  unarchive:
    src: '{{ app_directory }}/riot-v{{ riot_web_version }}.tar.gz'
    dest: '{{ nginx_webhost_directory }}/'
    remote_src: yes

- name: Copy the config file
  template:
    src: riot-web.json.j2
    dest: "{{ riot_web_directory }}/config.json"

- name: Create nginx config
  template:
    src: nginx.riot.conf.j2
    dest: "{{ nginx_config_directory }}/riot-smurfpandey-me.conf"
  notify: reload nginx

- name: Create CNAME record to point to the server
  cloudflare_dns:
    zone: "{{ riot_dns_zone }}"
    record: "{{ riot_dns_record }}"
    type: CNAME
    proxied: true
    value: "{{ riot_dns_value }}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
