control-machine:
    image: smurfpandey/ansible-cm:latest
    environment:
      SUDO_PASS: ${SUDO_PASS}
      VAULT_PASS: ${ANSIBLE_VAULT_PASS}
    volumes:
      - .:/ansible/playbooks
      - ~/.ssh/id_rsa:/tmp/.ssh/id_rsa:ro
