---
- hosts: all
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - { role: 'base-requirements' }
    - { role: 'fail2ban' }
    - { role: 'docker' }
    - { role: 'certbot' }
    - { role: 'ssl-neerajverma_dev' }
    - { role: 'nginx' }
    - { role: 'blog_smurfpandey_me' }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Your server is ready!"
