---
- hosts: all
  become: yes
  roles:
    - { role: 'base-requirements' }
    - { role: 'fail2ban' }
    - { role: 'docker' }
    - { role: 'certbot' }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Your server is ready!"
