---
- hosts: all
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - { role: 'base-requirements' }
    - { role: 'fail2ban' }
    - { role: 'docker' }
    - { role: 'certbot' }
    - { role: 'ssl-neerajverma_dev' }
    - { role: 'ssl-smurfpandey_me' }
    - { role: 'nginx', tags: 'nginx' }
    - { role: 'blog_smurfpandey_me' }
    - { role: 'comments_smurfpandey_me' }
    - { role: 'matrix_riot', tags: 'matrix_riot' }
    - { role: 'coturn_server', tags: 'coturn' }
    - { role: 'frps', tags: 'frps' }

  vars:
    ansible_become_pass: "{{ lookup('env','SUDO_PASS') }}"

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Your server is ready!"
