---
- name: Create blog app directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ app_directory }}"
    - "{{ content_directory }}"
    - "{{ mysql_data_directory }}"

- name: Pull required images from docker hub
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ ghost_image_tag }}"
    - "{{ mysql_image_tag }}"

- name: Create docker-compose.yml for blog
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"
  notify: restart blog_smurfpandey_me

- name: Create startup file for blog
  template:
    src: blog-service.sh.j2
    dest: "{{ app_directory }}/blog-service.sh"
    mode: 'a+x'

- name: Create nginx config for blog
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_directory }}/blog-smurfpandey-me.conf"
  notify: reload nginx

- name: Create blog service file
  template:
    src: blog_smurfpandey_me.service.j2
    dest: "{{ app_directory }}/blog_smurfpandey_me.service"
  notify: reload systemd

- name: Install blog service
  file:
    src: "{{ app_directory }}/blog_smurfpandey_me.service"
    dest: /etc/systemd/system/blog_smurfpandey_me.service
    state: link

- name: ensure blog starts on a fresh reboot
  service:
    name: blog_smurfpandey_me
    state: started
    enabled: yes

- name: Create CNAME record to point to the server
  cloudflare_dns:
    zone: "{{ blog_dns_zone }}"
    record: "{{ blog_dns_record }}"
    type: CNAME
    proxied: yes
    value: "{{ blog_dns_value }}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
