---

- name: Create comments app directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ app_directory }}"
    - "{{ data_directory }}"

- name: Pull required images from docker hub
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ remark42_image_tag }}"

- name: Create docker-compose.yml for app
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"
  notify: restart comments_smurfpandey_me

- name: Create nginx config for app
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_directory }}/comments-smurfpandey-me.conf"
  notify: reload nginx

- name: Create app service file
  template:
    src: comments_smurfpandey_me.service.j2
    dest: "{{ app_directory }}/comments_smurfpandey_me.service"
  notify: reload systemd

- name: Install app service
  file:
    src: "{{ app_directory }}/comments_smurfpandey_me.service"
    dest: /etc/systemd/system/comments_smurfpandey_me.service
    state: link

- name: ensure app starts on a fresh reboot
  service:
    name: comments_smurfpandey_me
    state: started
    enabled: yes

- name: Create CNAME record to point to the server
  cloudflare_dns:
    zone: "{{ app_dns_zone }}"
    record: "{{ app_dns_record }}"
    type: CNAME
    proxied: yes
    value: "{{ app_dns_value }}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
