---

- name: reload nginx
  command: docker kill --signal=HUP nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart blog_smurfpandey_me
  service:
    name: blog_smurfpandey_me
    state: restarted

- name: restart comments_smurfpandey_me
  service:
    name: comments_smurfpandey_me
    state: restarted

- name: restart matrix_smurfpandey_me
  service:
    name: matrix_smurfpandey_me
    state: restarted

- name: restart turn_neerajverma_dev
  service:
    name: turn_neerajverma_dev
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
