---
- name: Install certbot apt package
  apt:
    name:
      - certbot
      - python3-certbot-dns-cloudflare
    state: present
    install_recommends: no

- name: Create certbot app directory
  file:
    path: "{{ app_directory }}"
    state: directory

- name: Create Cloudflare credentials file
  template:
    src: cloudflare_credentials.ini.j2
    dest: "{{ app_directory }}/cloudflare_credentials.ini"

- name: check if a certbot account exists
  stat:
    path: /etc/letsencrypt/accounts
  register: letsencrypt_accounts_dir

- name: register certbot account
  command: >
    certbot register
    --email {{ certbot_register_email }}
    --non-interactive --agree-tos --quiet
  when: not letsencrypt_accounts_dir.stat.exists
