---
- name: ensure fail2ban is installed
  apt:
    pkg: fail2ban
    state: latest
    update_cache: yes
    install_recommends: no
    cache_valid_time: "{{ apt_cache_valid_time }}"
  notify:
    - restart fail2ban

- name: copy nginx filters
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/filter.d/{{ item }}"
  with_items:
    - nginx-http-auth.conf
    - nginx-noscript.conf
    - nginx-nohome.conf
    - nginx-noproxy.conf

- name: ensure fail2ban is configured
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  notify:
    - restart fail2ban


- name: ensure fail2ban starts on a fresh reboot
  service:
    name: fail2ban
    state: started
    enabled: yes
